Update build-aria2.yml

diff --git a/.github/workflows/build-aria2.yml b/.github/workflows/build-aria2.yml
--- a/.github/workflows/build-aria2.yml
+++ b/.github/workflows/build-aria2.yml
@@ -11,9 +11,15 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Install dependencies
-        run: sudo add-apt-repository ppa:ninja-build/ninja-stable
-             sudo apt update
-             sudo apt install -y ninja-build meson git wget
+        run: |
+          sudo add-apt-repository ppa:ninja-build/ninja-stable
+          sudo apt update
+          if [ $? -ne 0 ]; then
+            echo "Error: apt update failed"
+            exit 1
+          fi
+          sudo apt update
+          sudo apt install -y ninja-build meson git wget
       - name: Create dependencies directory
         run: mkdir -p dependencies
 
